### ISSUE TITLE
Invalid fødselsnummer when generating with a date

### ISSUE THREAD

**Issue by njanor** [hkhaug/nor-id-num#1]
When generating a new fødselsenummer using fromDate = toDate = 21.03.1975, the generator once returned 21037551446. This is a valid fødselsnummer, but implies a birth year where the century is even (i.e., 1875) which is invalid given the birth year 1975.

Edit: Removed 2075 as valid year.

**Comment by hkhaug** [comment]
You are right about this, there is a bug in the generation process. Thank you for letting me know. I will fix this issue as soon as possible.

**Comment by hkhaug** [comment]
The bug is fixed now.
