### ISSUE TITLE
< 1900

### ISSUE THREAD

**Issue by richardkarlsen** [hkhaug/nor-id-num#3]
Stemmer det at det ikke er støtte for fødselsnummer for før 1900? F.eks `01018487876` - `01.01.1884`

**Comment by hkhaug** [comment]
Hei!

Nei, det stemmer ikke. Lovlige fødselsnummer kan finnes helt fra 1854. Men de første tre sifrene etter datoen må være i området 500 til 749 (inklusive) for årstall fra 1854 til 1899. I eksempelet ditt er de tre sifrene 999 som betyr at årstallet er i området 1940 til 1999, og dermed blir datoen 01.02.1989, ikke 01.02.1889. Disse reglene er oppsummert her: https://www.skatteetaten.no/Person/Folkeregister/Fodsel-og-navnevalg/Barn-fodt-i-Norge/Fodselsnummer

Mvh
Hans Kristian Haug

**Comment by richardkarlsen** [comment]
Hei!

Får ikke helt 01018487876 til å stemme med det du forklarer. For 01018487876 så er vel 878 individnummer. Det ville vel bety at det er i serien "2000-2039, brukes serien 999-500" ref https://www.skatteetaten.no/Person/Folkeregister/Fodsel-og-navnevalg/Barn-fodt-i-Norge/Fodselsnummer?

**Comment by hkhaug** [comment]
Hei!

01018487876 er ikke et lovlig fødselsnummer. Årstallet 84 og individnummeret 878 kan ikke kobles sammen i henhold til tabellen på siden hos skatteetaten:

  1.  1854-1899, brukes serien 749-500
  2.  1900-1999, brukes serien 499-000
  3.  1940-1999, brukes også serien 999-900
  4.  2000-2039, brukes serien 999-500
Individnummeret 878 kan bare finnes i serien 999-500, som er knyttet til årstallene 2000-2039. Men årstallet 84 passer ikke inn i den årstallserien – det er bare årstall 00 til 39 som passer. Dermed blir kombinasjonen av årstallet 84 og individnummeret 878 ulovlig.

Håper det var oppklarende.

Mvh
Hans Kristian Haug
